[package]
name = "amazon-price-scraper"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
scraper = "0.12.0"
reqwest = "0.10.8"
prettytable-rs = "0.8.0"
textwrap = "0.12.1"
url = "2.1.1"
anyhow = "1"
async-std = {version = "1", features = ["attributes", "tokio02"]}
futures = "0.3.6"

[profile.dev]
opt-level = 1

[profile.release]
opt-level = 2
debug = false
# lto = true